[package]
name = "backup-service"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
aide = { version = "0.14.2", features = [
    "redoc",
    "swagger",
    "scalar",
    "axum-json",
    "macros",
] }
axum = { version = "0.8.1", features = ["macros"] }
tower-http = { version = "0.6.2", features = ["compression-br", "limit", "trace", "timeout"] }
schemars = "0.8.21"

aws-config = "1.6.0"
aws-sdk-kms = "1.63.0"
aws-sdk-s3 = "1.79.0"

anyhow = "1.0.97"
base64 = "0.22.1"
dotenvy = "0.15.7"
futures = "0.3.31"
josekit = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["fmt", "json"] }
uuid = { version = "1.16.0", features = ["v4", "serde"] }
http = "0.2.12"
# TODO/FIXME: Investigate how dangerous this is considering we're going to be tracking used challenges
webauthn-rs = { version = "0.5.1", features = ["danger-allow-state-serialisation"] }

[dev-dependencies]
http-body-util = "0.1.3"
tower = "0.5.2"