name: backup-service
services:
  redis-backup-service:
    image: redis:latest
    ports:
      - "6379:6379"
  localstack-backup-service:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,kms,dynamodb
      - DISABLE_EVENTS=1
    volumes:
      - /var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - "./tests/aws-seed.sh:/etc/localstack/init/ready.d/aws-seed.sh"
