name: backup-service
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,kms,dynamodb
      - DISABLE_EVENTS=1
    volumes:
      - /var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - "./tests/aws-seed.sh:/etc/localstack/init/ready.d/aws-seed.sh"