name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Format & Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Build the project
        run: cargo build --release

  build-release:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update

      - name: Build the project
        run: cargo build --release

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update

      - name: Start LocalStack
        run: |
          docker compose up -d
          # Wait for services to be ready
          sleep 5

      - name: Health check LocalStack
        run: curl -s http://localhost:4566/_localstack/health | jq -e '.services.s3 == "running"'

      - name: Run tests
        run: cargo test -- --nocapture

      - name: Clean up
        run: docker compose down

  docker:
    name: Test Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: backup-service-ci:latest
          secrets: |
            GITHUB_TOKEN=${{ secrets.GIT_HUB_TOKEN }}
          cache-from: type=gha
          cache-to: "type=gha,mode=max"

      - name: Docker Compose services
        run: |
          docker compose up -d

      - name: Run Docker container
        run: |
          docker run -d --network host --env-file .env.example --name backup-service-ci-container backup-service-ci:latest

          # Wait for the application to start
          sleep 10

          # Output logs to GitHub action
          docker logs backup-service-ci-container

      - name: Health check Docker container
        run: curl -f http://0.0.0.0:8000/

      - name: Clean up
        run: |
          docker stop backup-service-ci-container
          docker rm backup-service-ci-container
          docker compose down

  deny:
    name: Cargo deny
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update

      - name: Install cargo-deny
        run: cargo install --locked cargo-deny

      - name: Check
        run: cargo deny check
